name: .NET Build

on:
  push:
    branches:
    - master
    - ci
  pull_request:

env:
  artifact: EsnyaResoniteModTemplate.dll

jobs:
  vtag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find csproj file
        id: find_csproj
        run: |
          echo "ProjectFile=$(find . -name "*.csproj" | head -n 1)" >> $GITHUB_OUTPUT

      - name: Get version from csproj
        id: get_version
        run: |
          echo "Version=$(grep -oPm1 "(?<=<Version>)[^<]+" ${{ steps.find_csproj.outputs.ProjectFile }})" >> $GITHUB_OUTPUT

      - name: Pull tags
        run: git fetch --tags

      - name: Check if tag exists
        id: check_tag
        run: |
          echo "TagExists=$(git tag -l "v${{ steps.get_version.outputs.Version }}")" >> $GITHUB_OUTPUT

      - name: Create tag
        if: steps.check_tag.outputs.TagExists == ''
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git tag "v${{ steps.get_version.outputs.Version }}"
          git push origin "v${{ steps.get_version.outputs.Version }}"
    outputs:
      tagged: ${{ steps.check_tag.outputs.TagExists == '' }}
      tag: v${{ steps.get_version.outputs.Version }}

  build:
    runs-on: windows-latest
    steps:
    - id: checkout
      name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Build RML mod
      uses: esnya/build-rml-mod@v1
      with:
        project: ${{ github.workspace }}
        steam-login: ${{ secrets.STEAMLOGIN }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.artifact }}
        path: bin/Release/${{ env.artifact }}

  release:
    if: startsWith(github.ref, 'refs/tags/v') || needs.vtag.outputs.tagged
    needs:
      - vtag
      - build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref:  ${{ needs.vtag.outputs.tagged && needs.vtag.outputs.tag || github.ref }}
        fetch-depth: 0
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        name: ${{ env.artifact }}
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ${{ env.artifact }}
        generate_release_notes: true
        tag_name: ${{ needs.vtag.outputs.tagged && needs.vtag.outputs.tag || github.ref }}
